name: Build

on:
  push:

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10
    
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Execute patch
      run: ./gradlew applypatches

    - name: Execute jar build
      run: ./gradlew createMojmapPaperclipJar

    - name: Save jar
      uses: actions/upload-artifact@v3
      if: always()
      with: 
        name: precompiled
        path: precompiled/
